version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run scraper
  node_calculator:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    command: npm run calculator
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
      - ./docker_files/mongodb/:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thibault
      - MONGO_INITDB_ROOT_PASSWORD=kSWDmp5VP5xjFVf8b4XcDq
      - MONGO_INITDB_DATABASE=MIVB
  nodejs:
    image: node:alpine
    container_name: nodejs
    restart: unless-stopped
    working_dir: /app
    environment: 
      NODE_ENV: production
    networks:
      - app-network
    volumes:
      - ./:/app
    command: npm run webserver
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker_files/nginx/:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  mongo_db:

networks:
  app-network:
    driver: bridge